### ISSUE TITLE
关于学习率计算代码报错

### ISSUE THREAD

**Issue by 13871414179** [AlexZou14/Wave-Mamba#6]
Traceback (most recent call last):
  File "basicsr/train.py", line 272, in <module>
    train_pipeline(root_path)
  File "basicsr/train.py", line 212, in train_pipeline
    model.update_learning_rate(current_iter, warmup_iter=opt['train'].get('warmup_iter', -1))
  File "/opt/data/private/Wave-Mamba-main/basicsr/models/base_model.py", line 198, in update_learning_rate
    scheduler.step()
  File "/root/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/optim/lr_scheduler.py", line 230, in step
    values = self.get_lr()
  File "/opt/data/private/Wave-Mamba-main/basicsr/models/lr_scheduler.py", line 96, in get_lr
    current_weight = self.restart_weights[idx]
TypeError: list indices must be integers or slices, not NoneType
![QQ_1726745983933](https://github.com/user-attachments/assets/a38575dc-e21f-4a0a-8ebe-1713047fa61b)
你好，在训练过程中我遇到了以上问题，我看到你代码这边有相关注释，想问问你了解这边的原因吗？

**Comment by AlexZou14** [comment]
你的配置文件是不是修改了iter和lr

**Comment by 13871414179** [comment]
我没有进行修改，这段错误是在运行快要结束是发生的

**Comment by AlexZou14** [comment]
那不用管他 这个bug不影响训练

**Comment by ZXXaaaa** [comment]
您好，请问您大概训练了多长时间

**Comment by Huuuuuuhub** [comment]
> 你的配置文件是不是修改了iter和lr

你好，请问 我修改了iter，出现了上面这种错误，该如何解决

**Comment by AlexZou14** [comment]
你好是一开始就遇上了还是说，训练到了最后

**Comment by AlexZou14** [comment]
> 您好，请问您大概训练了多长时间
lol数据集是大概两天的样子
uhdll要更久一些
